# Generated by Django 4.1 on 2023-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=''),
        ),
    ]
