# Generated by Django 4.1 on 2023-10-03 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0002_alter_expense_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 3, 3, 58, 32, 9405), null=True, verbose_name=''),
        ),
    ]
