# Generated by Django 4.1 on 2023-10-03 03:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExpenseApp', '0003_alter_expense_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 3, 4, 20, 43, 835715), null=True, verbose_name=''),
        ),
    ]
