# Generated by Django 4.1 on 2023-10-03 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0004_expense_owner_alter_expense_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 3, 4, 26, 22, 746792), null=True, verbose_name=''),
        ),
    ]
